networks:
  prod-public:
    driver: bridge
  prod-private:
    driver: bridge
    # TODO: for best security, this should be set to true. But that is probably
    # overkill. Then backend containers would have no internet access at all. 
    internal: false

services:
  # 1) Install deps ONCE for the whole repo (root lockfile)
  deps:
    networks:  !override [prod-private]

  # 2) Frontend (Vite dev server)
  frontend:
    ports: !reset []
    networks:  !override [prod-private]

  # 3) Backend (Fastify + tsx watch)
  backend:
    ports: !reset []
    networks:  !override [prod-private]

  # 4) Nginx (single-origin dev, optional but convenient)
  nginx:
    networks:  !override [prod-public, prod-private]

  # 5) Matchmaking service (WebSocket server)
  matchmaking-service:
    ports: !reset []
    networks:  !override [prod-private]

# 6) Game server (WebSocket server)
  game-server:
    ports: !reset []
    networks: !override [prod-private]

