POST http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwidXVpZCI6IjU4OTUwZDk4LTc4YmMtNDc1OS1hYTE4LTQ2MDdlNjRmM2EwMCIsImlhdCI6MTc1Njk5MDExOCwiZXhwIjoxNzU3MDA0NTE4fQ.Ni4z_lbk69AcH6jMNibSbbL7Zby7Lr-laWTmErAB4Pw
