DELETE http://localhost:3001/api/users/9da860c3-7d26-4af5-bcc9-002d8541d2d8/avatar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyMiIsInV1aWQiOiI5ZGE4NjBjMy03ZDI2LTRhZjUtYmNjOS0wMDJkODU0MWQyZDgiLCJpYXQiOjE3NTU2ODU4MzksImV4cCI6MTc1NTY4OTQzOX0.ie-Dn_LLYsRQhNzFxVhHRuqO7EbTac4LuCcF9B82xnA
