PATCH http://localhost:3001/api/users/me/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwidXVpZCI6IjcxNGM4ZjA4LTI3OGItNDA4OC1iMDAwLTdjMDg4ZGY0YzRiNiIsImlhdCI6MTc1NTcxNDUzNSwiZXhwIjoxNzU1NzE4MTM1fQ.fk06f4NHiMpiSMwEOylhbuYmw1KDxH3cWM0101Y4SAk
Content-Type: application/json

{
	"currentPassword": "testPassword2",
	"newPassword": "testPassword1"
}
