POST http://localhost:3001/api/users/me/confirm-delete/8afc7e4a2a062a7abd20997e51b394144cdac2aee352c1b0d380af360bb4335c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwidXVpZCI6ImI1ZDM2MWZlLWVhZDAtNDY3Zi1hYzEwLTljZmU5ZmVmMDhkOSIsImlhdCI6MTc1NjMxMDU3MiwiZXhwIjoxNzU2MzI0OTcyfQ.B_piYv5z24HncSwpTXGjGW34HFtUPlKwJEi1ePWdQg0
