PUT http://localhost:3001/api/users/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyMiIsInV1aWQiOiI4NDZjZGFiOC1jNTYzLTQyMTctYWQxNi02YzdiMzBhN2E3ZDAiLCJpYXQiOjE3NTU2MDMxNzQsImV4cCI6MTc1NTYwNjc3NH0.Gpxi_sot0Lux26rXilUKjgewSX2K0jKJqOzq7C0kf_I
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"

------WebKitFormBoundary7MA4YWxkTrZu0gW--

## When "avatar" is present in the request but empty, it means delete it from database.
