input {
  gelf {
    port => 12201
  }
}

# if message starts with '{', parse it as JSON
filter {
  if [message] =~ /^\{/ {
    json {
      source => "message"
      target => "parsed"
      # tag_on_exception => [ "_jsonparsefailure" ]
	}
  }
}

output {
 elasticsearch {
   index => "logstash-%{+YYYY.MM.dd}"
   hosts=> "${ELASTIC_HOSTS}"
   user=> "${ELASTIC_USER}"
   password=> "${ELASTIC_PASSWORD}"
   ssl_certificate_authorities=> ["/usr/share/logstash/certs/ca/ca.crt"]
 }
}
