input {
  gelf {
    port => 12201
  }
}

filter {

  # if message starts with '{', parse it as JSON, this is for our Node.js services
  if [message] =~ /^\{/ {
    json {
      source => "message"
      target => "json"
    }
  }

  # nginx
  else if "nginx" in [container_name] {
    grok {
    match => { "message" => "%{IPORHOST:clientip} (?:-|(%{WORD}.%{WORD})) %{USER:ident} \[%{HTTPDATE:timestamp}\] \"(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})\" %{NUMBER:response} (?:%{NUMBER:bytes}|-) %{QS:referrer} %{QS:agent} %{QS:forwarder}"
      }
      target => "nginx"
    }
  }

  # redis
  else if "redis" in [container_name] {
    grok {
      match => { "message" => "%{NUMBER:pid}:%{WORD:role} %{MONTHDAY} %{MONTH} %{YEAR} %{TIME} %{NOTSPACE:loglevel} %{GREEDYDATA:msg}" }
      target => "redis"
    }
    translate {
      source       => "[redis][loglevel]"
      target => "[redis][loglevel]"
      dictionary  => {
        "." => "debug"
        "-" => "verbose"
        "*" => "notice"
        "#" => "error"
      }
      fallback    => "unknown"
    }
  }
}

output {
  elasticsearch {
    index => "logstash-%{+YYYY.MM.dd}"
    hosts=> "${ELASTIC_HOSTS}"
    user=> "${ELASTIC_USER}"
    password=> "${ELASTIC_PASSWORD}"
    ssl_certificate_authorities=> ["/usr/share/logstash/certs/ca/ca.crt"]
  }
}
