GET http://localhost:3001/api/matches/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IldpbCIsInV1aWQiOiIxYmY4NGNhZi1kY2IxLTQyNzctOGY0ZC1kMDE3OGMzMTMyOWUiLCJpYXQiOjE3NTgxMzE1NjksImV4cCI6MTc1ODE0NTk2OX0.tjrNnX4OsTmWSf262qCYpKrcevimlx_rRVZciB1fmfo
