networks:
  prod-private:
    driver: bridge
    internal: true
  prod-public:
    driver: bridge

volumes:
  grafana-storage:
    driver: local
  prometheus-config:
    driver: local
  alertmanager-config:
    driver: local

services:

  prometheus-pre:
    build:
      context: ./monitoring/prometheus-pre/
    environment:
      - ALLOCATOR_PORT=${ALLOCATOR_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - MATCHMAKING_PORT=${MATCHMAKING_PORT}
      - SCORER_PORT=${SCORER_PORT}
      - CHAT_PORT=${CHAT_PORT}
      - GAME_SERVER_HTTP=${GAME_SERVER_HTTP}
      - GAME_SERVER_PORT=${GAME_SERVER_PORT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_FROM_RAW=${MAIL_FROM_RAW}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - ALERT_MAIL_TO=${ALERT_MAIL_TO:-test@example.com}
      - ALERT_WEBHOOK_URL=${ALERT_WEBHOOK_URL}
    volumes:
      - prometheus-config:/etc/prometheus
      - alertmanager-config:/etc/alertmanager
    restart: no

  prometheus:
    image: prom/prometheus:v3.7.3
    restart: unless-stopped
    depends_on:
      prometheus-pre:
        condition: service_completed_successfully
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=1GB'
    volumes:
      - prometheus-config:/etc/prometheus:ro
    networks:
      - prod-private

  alertmanager:
    image: prom/alertmanager:v0.29.0
    restart: unless-stopped
    depends_on:
      prometheus-pre:
        condition: service_completed_successfully
    volumes:
      - alertmanager-config:/etc/alertmanager:ro
    networks:
      - prod-private
      - prod-public

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.0
    depends_on:
      nginx:
        condition: service_started
    command:
      - '--nginx.scrape-uri=http://nginx:${NGINX_STUB_STATUS_PORT:-8081}/stub_status'
    networks:
      - prod-private

  grafana:
    image: grafana/grafana:12.2.1
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
      - GF_SERVER_ROOT_URL=${FRONTEND_URL}/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_ENABLE_GZIP=true
      - GF_SERVER_ROUTER_LOGGING=true
      - GF_AUTH_GOOGLE_CLIENT_ID=${GRAFANA_OAUTH_CLIENT_ID}
      - GF_AUTH_GOOGLE_CLIENT_SECRET=${GRAFANA_OAUTH_CLIENT_SECRET}
      - GF_AUTH_GOOGLE_REDIRECT_URI=http://localhost:${GRAFANA_PORT:-3002}/grafana/login/google
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=${GRAFANA_PORT:-3002}
      - GF_SERVER_ENFORCE_DOMAIN=false
      - GF_SECURITY_COOKIE_SAMESITE=lax
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards/:/etc/grafana/dashboards
    healthcheck:
      test:
        - CMD-SHELL
        - |
          curl -sf http://localhost:${GRAFANA_PORT:-3002}/api/health \
          | grep -q '"database": "ok"'
      interval: 5s
      timeout: 5s
      retries: 100
    networks:
      - prod-private
      - prod-public

  grafana-setup:
    build:
      context: ./monitoring/grafana-setup/
    depends_on:
      grafana:
        condition: service_healthy
    environment:
      - GRAFANA_URL=http://grafana:${GRAFANA_PORT:-3002}
      - ADMIN_USER=${GRAFANA_ADMIN_USER}
      - ADMIN_PASS=${GRAFANA_ADMIN_PASS}
      - EDITOR_NAME=${GRAFANA_EDITOR_NAME}
      - VIEWER_NAME=${GRAFANA_VIEWER_NAME}
    networks:
      - prod-private

  # How much cAdvisor can do really depends how much privileges you have
  # on the host. Enabling too many things will fill the logs with spam and
  # eat the CPU.
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    restart: unless-stopped
    privileged: true
    command:
      - '--disable_metrics=cpu_topology,disk,network,memory,memory_numa,tcp,udp,percpu,sched,process,hugetlb,referenced_memory,resctrl,cpuset,advtcp'
      - '--docker_only=true'
      - '--housekeeping_interval=30s'
    cap_add:
      - SYS_PTRACE
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      - prod-private
