services:

  prometheus-pre:
    networks:
      - devnet

  prometheus:
    networks:
      - devnet
    ports:
      - '9090:9090'

  alertmanager:
    networks:
      - devnet
    ports:
      - '9093:9093'

  nginx-exporter:
    networks:
      - devnet
    ports:
      - '9113:9113'

  grafana:
    networks:
      - devnet
    ports:
      - '3002:3002'
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3002/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false

  grafana-setup:
    networks:
      - devnet
    environment:
      - GRAFANA_URL=http://grafana:3002

  cadvisor:
    networks:
      - devnet
    ports:
      - '8090:8080'
