volumes:
  grafana-storage:
    driver: local

# TODO: labels?
services:
  prometheus:
    image: prom/prometheus
    profiles:
      - monitoring
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - devnet
    ports:
      - "9090:9090"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    profiles:
      - monitoring
    command:
      - "-nginx.scrape-uri=http://nginx:80/stub_status"
    networks:
      - devnet
    ports:
      - "9113:9113"

  grafana:
    image: grafana/grafana
    profiles:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASS}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    networks:
      - devnet
    ports:
      - "3002:3000"

  grafana-setup:
    image: alpine:3
    profiles:
      - monitoring
    depends_on:
      - grafana
    volumes:
      - ./grafana-setup/setup.sh:/setup.sh:ro
    environment:
      - GRAFANA_URL=http://grafana:3000
      - ADMIN_USER=${GRAFANA_ADMIN_USER}
      - ADMIN_PASS=${GRAFANA_ADMIN_PASS}
      - NEW_NAME=${GRAFANA_USER_NAME}
      - NEW_LOGIN=${GRAFANA_USER_NAME}
      - NEW_PASS=${GRAFANA_USER_PASS}
    networks:
      - devnet
    entrypoint: ["sh", "/setup.sh"]

  # How much cAdvisor can do really depends how much privileges you have
  # on the host. Enabling too many things will fill the logs with spam.
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    profiles:
      - monitoring
    command:
      - "--disable_metrics=disk,percpu,network,memory,referenced_memory"
    # privileged: true
    ports:
      - "8090:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      # - "/proc:/host/proc:ro"
      # - "/dev/disk/:/dev/disk:ro"
    # devices:
    #   - "/dev/kmsg:/dev/kmsg"
    networks:
      - devnet
