services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3002:3000"

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   ports:
  #     - "8080:8080"

  # nginx-exporter:
  #   image: nginxinc/nginx-prometheus-exporter:latest
  #   command:
  #     - "-nginx.scrape-uri=http://nginx:80/stub_status"
  #   ports:
  #     - "9113:9113"
