services:

  prometheus-pre:
    networks:
      - devnet

  prometheus:
    networks:
      - devnet
    ports:
      - '9090:9090'

  nginx-exporter:
    networks:
      - devnet
    ports:
      - '9113:9113'

  grafana:
    networks:
      - devnet
    ports:
      - '3002:3000'
    environment:
      - GF_SERVER_ROOT_URL=https://localhost:3000/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false

  grafana-setup:
    networks:
      - devnet
    environment:
      - GRAFANA_URL=http://grafana:3000

  cadvisor:
    networks:
      - devnet
    ports:
      - '8090:8080'
