services:

  prometheus-pre:
    networks:
      - devnet

  prometheus:
    networks:
      - devnet
    ports:
      - '9090:9090'

  nginx-exporter:
    networks:
      - devnet
    ports:
      - '9113:9113'

  grafana:
    networks:
      - devnet
    ports:
      - '3002:3000'

  grafana-setup:
    networks:
      - devnet

  cadvisor:
    networks:
      - devnet
    ports:
      - '8090:8080'
