POST http://localhost:3001/api/friends/e382b807-8378-44cb-af6e-2e3b782923a7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwidXVpZCI6IjcxNGM4ZjA4LTI3OGItNDA4OC1iMDAwLTdjMDg4ZGY0YzRiNiIsImlhdCI6MTc1NTcxNTEyMCwiZXhwIjoxNzU1NzE4NzIwfQ.uurQzRlt0OnYlXHO8Ec3x6BJdYboiHL7W43kwD13r7Q
