services:

  elastic_cert_setup:
    networks:
      - devnet

  elasticsearch:
    ports:
      - ${ES_PORT}:9200
    networks:
      - devnet

  # configures policies using the API
  elasticsearch-post:
    networks:
      - devnet

  kibana:
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVER_BASEPATH=
      - SERVER_PUBLICBASEURL=${FRONTEND_URL}
    networks:
      - devnet

  kibana-post:
    networks:
      - devnet

  logstash:
    ports:
      - '12201:12201/udp' # Listening port for logs
      - '9600:9600'      # Logstash monitoring API
    networks:
      - devnet
