{
 "title": "Node.js & SQLite Metrics",
 "tags": [
  "sqlite",
  "prometheus",
  "nodejs"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Request Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Memory (RSS) megabytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"node-backend\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds" }
   ]
  },
  {
   "title": "SQL query rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(sqlite_query_total[$__rate_interval])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "SQLite Query Duration (avg seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(sqlite_query_duration_seconds_sum[5m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "SQL Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sqlite_query_errors_total or vector(0)",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}