name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - feat/devops-test
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .env
        run: cp .env.example .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all services
        run: make detached

      - name: Stop all services
        run: make down

      - name: Clean everything
        run: make fclean
